// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/cloudwego/kitex-layout/internal/config"
	"github.com/cloudwego/kitex-layout/internal/infrastructure/repository"
	"github.com/cloudwego/kitex-layout/internal/usecase"
	"github.com/cloudwego/kitex-layout/kitex_gen"
)

// Injectors from wire.go:

func initHandler(db *config.DB) kitex_gen.World {
	gormDB := repository.NewGorm(db)
	usecaseRepository := repository.NewWorldSQL(gormDB)
	world := usecase.NewService(usecaseRepository)
	return world
}
